### PR TITLE
Name the build id argument BUILD

### PR DESCRIPTION
**Pull request by dmathieu**
For consistency with the builds:info command

### CODE REVIEW

**Comment by bigkevmcd** [comment]
👍  thank you!

Also, it could do with a table to explain what each of the columns is ;-)

There are two values that look like they're IDs which is why I was confused, because there are two values, and two different names for the same value...

**Comment by dmathieu** [comment]
Yeah, the info output could definitely be made clearer. There was a reason we didn't add a header, but I don't remember what it is.

**Comment by bigkevmcd** [comment]
@dmathieu doesn't need fixed in this branch, but not remembering suggests it's not a really strong reason for not including a header :-)

**Comment by bigkevmcd** [comment]
Unless we don't really want users using this?

**Pull request merged**
