### PR TITLE
update dependencies

### LINKED ISSUE #19: Fatal error on Heroku Toolbelt 3.43.0
When attempting to run `heroku builds:create` on Heroku Toolbelt 3.43.0 I get the following error:

```
buffer.js:106
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:106:13)
    at Readable.<anonymous> (/Users/Tend/.local/share/heroku/plugins/node_modules/archiver/lib/util/index.js:32:15)
    at emitNone (events.js:91:20)
    at Readable.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

We rely on this plugin for our build process and I'm happy to make a fix if I can. I'd love some insight into where to start looking. Any ideas?

### PR DESCRIPTION
**Pull request by dickeyxxx**
Fixes #19

### CODE REVIEW

**Comment by dickeyxxx** [comment]
cc @tt

**Comment by tt** [comment]
Looks good to me.

**Comment by dickeyxxx** [comment]
@tt looks like I don't have access to publish this to npm, mind adding me to it?

**Comment by dickeyxxx** [comment]
@tt nevermind, itops was added so I was able to push

**Pull request merged**
